
export const portfolio = [
    {
        id: "1",
        title: "Ecommerce",
        name: "SonhoVeg",
        description: "Este é um site de vendas de doces, onde há pagamentos, contas, painel de controle para administrar praticamente tudo que acontece no site, status das comidas e agendamento para entrega e muito mais. Este é um dos sites mais completos que já fiz, ainda não está totalmente completo, mas as principais funcionalidades está tudo funcionando muito bem.",
        link: "https://sonhoveg.com/",
        image: "/sonhoveg.svg",
        reverse: true,
    },
    {
        id: "8",
        title: "Ecommerce App",
        name: "Aplicativo de ecommerce",
        link: "https://github.com/wallace2001/app_ecommerce_project",
        description: "Um aplicativo simples simulando um ecommerce, com muitas funcionalidades como, animações, rotas autenticadas, tab bar, sistema de carrinho, swipeable...",
        image: "/app.jpeg",
        reverse: false,
    },
    {
        id: "2",
        title: "Site Portfólio",
        name: "Site Portfólio",
        link: "#",
        description: "Um site para mostrar meus trabalhos e contar um pouco sobre minha trajetória nesse mundo da programação.",
        image: "/port.svg",
        reverse: true,
    },
    {
        id: "3",
        title: "Vendas",
        name: "Site de vendas de sprites",
        description: "Este site é um site de vendas de sprites para jogos, possui um painel de controle muito completo para gerenciar tudo que acontce no site. E o melhor, este site possui um sistema de chat em tempo real para tirar dúvidas.",
        link: "#",
        image: "/mark.svg",
        reverse: false,
    },
    {
        id: "4",
        title: "Quiz",
        name: "Jogo Quiz",
        description: "Foi desenvolvido para fins acadêmicos, é um site bem legal, onde possui um ranking e vários quizes.",
        link: "https://quiz-school-word.vercel.app/",
        image: "/quiz_my.svg",
        reverse: true,
    },
    {
        id: "5",
        title: "Quiz",
        name: "Jogo Quiz",
        description: "Esse outro quiz foi desenvolvido a muito tempo, em uma semana gratuita de aula da alura. Portanto eu modifiquei muitas coisas, como as perguntas estarem salvas no banco de dados e um rankin ordenados.",
        link: "https://quiz-two-indol.vercel.app/",
        image: "/quiz.svg",
        reverse: false,
    },
    {
        id: "6",
        title: "Restaurante",
        name: "Site de demonstração de um restaurante",
        description: "Este site também possui muito tempo que desenvolvi, ele tem a finalidade de ser como um cardápio e também possui um painel de controle para gerenciar praticamente tudo do site.",
        link: "https://fronted-delivery.vercel.app/",
        image: "/hamb.svg",
        reverse: true,
    },
    {
        id: "7",
        title: "Aplicativo",
        name: "Chat em tempo real",
        link: "#",
        description: "Este aplicativo foi desenvolvido para ser usado apenas por uma pessoa. Ele possui um sistema de chat em tempo real para conversarem com pessoas que entram em contato pelo site dele.",
        image: "/app.svg",
        reverse: false,
    },
];